language: ruby

cache: bundler

rvm:
- 2.4.1

before_script:
- gem update bundler  
script:
- bundle exec jekyll build

branch:
- master

deploy:
  provider: s3
  bucket: www.jonstites.com  
  skip_cleanup: true
  local_dir: _site
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: $AWS_SECRET_KEY
  region: $AWS_DEFAULT_REGION
  cache_control: "max-age=31536000"
