language: node_j

node_js:
  - "13"

cache: yarn

script:
- yarn build

branch:
- master
- feature/vuepress

deploy:
  provider: s3
  bucket: www.jonstites.com  
  skip_cleanup: true
  local_dir: blog/.vuepress/dist/
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: $AWS_SECRET_KEY
  region: $AWS_DEFAULT_REGION
  cache_control: "max-age=31536000"
